name: Wilson Page
description: "Wilson is a front-end developer working at Mozilla. He is currently working on Firefox OS, specialising in performant mobile web applications."
url: http://wilsonpage.co.uk
permalink: /:title
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
pygments: true
exclude: [
  'components',
  'node_modules',
  'GruntFile.js',
  'package.json'
]

