name: Wilson Page
description: "Wilson is a front-end developer at <a href='http://twitter.com/ftlabs'>FT Labs</a>, within the Financial Times."
url: http://wilsonpage.co.uk
permalink: /:title
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
pygments: true
exclude: [
  'css',
  'node_modules',
  'GruntFile.js',
  'package.json'
]

