name: Wilson Page
description: A description for your blog
url: http://wilsonpage.co.uk
permalink: /:title
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
pygments: true
exclude: [
  'css',
  'node_modules',
  'GruntFile.js',
  'package.json'
]

