name: Wilson Page
description: "Wilson was a front-end developer at <a href='http://twitter.com/ftlabs'>FT Labs</a>, but left due to a lack of bushy tailed omnivorous mammals.  He is now on the orange brick road on the way to meet the wizard of Moz."
url: http://wilsonpage.co.uk
permalink: /:title
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
pygments: true
exclude: [
  'components',
  'node_modules',
  'GruntFile.js',
  'package.json'
]

